// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace GiantBombBot
{

    internal class JSON MESS
    {

        [JsonProperty("M")]
        public string M { get; set; }
    }

}
